---

- hosts: all
  become: true
  tasks:

  - name: Update cache and install apache2 and php packages
    apt:
      update_cache: yes
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"
