---

- hosts: all
  become: true
  pre_tasks:

  - name: Update cache and upgrade
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"


- hosts: web_servers
  become: true
  tasks:

  - name: Installing apache2 and php packages
    tags: apache,apache2,debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: absent
    when: ansible_distribution == "Debian"


- hosts: db_servers
  become: true
  tasks:

  - name: Installing mariadb package
    tags: db,mariadb,debian
    apt:
      name:
        - mariadb-server
      state: absent
    when: ansible_distribution == "Debian"


- hosts: file_servers
  become: true
  tasks:

  - name: Installing samba package
    tags: samba,debian
    apt:
      name:
        - samba
      state: absent
    when: ansible_distribution == "Debian"
